server:
  port: 8081

spring:
  cloud:
    stream:
      bindings:
        smsVerificationCreatedPublish:
          destination: sms-verification-delivered
        smsVerificationDeliveredSubscribe:
          destination: sms-verification-created
